version: '3.3'

services:
  movienator-express-dev:
    build:
      context: ./movienator_express
      dockerfile: Dockerfile
    container_name: movienator-express-dev
    environment:
      TZ: 'Europe/Berlin'
      DB_PASSWORD: 'root'
      DB_USERNAME: 'root'
      DB_HOST: 'database'
      DB_NAME: 'movienator-database'
      MOVIE_API_KEY: ${MOVIE_API_KEY}
      HATESPEECH_API_KEY: ${HATESPEECH_API_KEY}
    ports:
      - '8080:8080'
      - '9229:9229'
    volumes:
      - ./movienator_express:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - movienator_network
    command: npm run install-start

  database:
    build:
      context: ./movienator_mysql
      dockerfile: Dockerfile
    container_name: movienator-database-dev
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: movienator-database
      MYSQL_USER: public
      MYSQL_PASSWORD: public
      LANG: C.UTF-8
    ports:
      - '3306:3306'
    volumes:
      - dbdata:/var/lib/mysql
      - ./movienator_mysql/sqlDump.sql:/docker-entrypoint-initdb.d/1.sql
    networks:
      - movienator_network
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  phpadmin:
    build:
      context: ./movienator_phpadmin
      dockerfile: Dockerfile
    container_name: movienator-phpadmin
    networks:
      - movienator_network
    ports:
      - '8081:80'
    environment:
      PMA_HOST: database
      PMA_PORT: 3306

  react:
    build:
      context: ./movienator_react
      dockerfile: Dockerfile
    container_name: movienator-react-dev
    stdin_open: true
    ports:
      - '3000:3000'
    volumes:
      - ./movienator_react:/usr/src/app/
      - /usr/src/app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: 'true'
    depends_on:
      - movienator-express-dev
    command: npm run install-start

volumes:
  dbdata:

networks:
  movienator_network:
    driver: bridge
