version: '3.9'

services:
  movienator-express-test:
    build:
      context: ./movienator_express
      dockerfile: Dockerfile
    container_name: movienator-express-test
    environment:
      TZ: 'Europe/Berlin'
      DB_PASSWORD: ${DB_PASSWORD}
      MOVIE_API_KEY: ${MOVIE_API_KEY}
    ports:
      - '8080:8080'
      - '9229:9229'
    volumes:
      - ./movienator_express:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - database-test
    networks:
      - movienator_network
    command: npm run install-test

  database-test:
    build:
      context: ./movienator_mysql_test
      dockerfile: Dockerfile
    container_name: movienator-database-test
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: movienator-database-test
      MYSQL_USER: public
      MYSQL_PASSWORD: public
    ports:
      - '3307:3306'
    networks:
      - movienator_network

  react-test:
    build:
      context: ./movienator_react
      dockerfile: Dockerfile
    container_name: movienator-react-test
    stdin_open: true
    ports:
      - '3000:3000'
    volumes:
      - ./movienator_react:/usr/src/app/
      - /usr/src/app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: 'true'
      HATESPEECH_API_KEY: ${HATESPEECH_API_KEY}
    depends_on:
      - movienator-express-test
    command: npm run install-test

networks:
  movienator_network:
    name: movienator_net
    driver: bridge
