version: '3.3'

services:
  movienator-express-dev:
    build:
      context: ./movienator_express
      dockerfile: Dockerfile
    container_name: movienator-express-dev
    environment:
      TZ: 'Europe/Berlin'
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USERNAME: 'sql11591037'
      DB_HOST: 'sql11.freesqldatabase.com'
      DB_NAME: 'sql11591037'
      MOVIE_API_KEY: ${MOVIE_API_KEY}
      HATESPEECH_API_KEY: ${HATESPEECH_API_KEY}
    ports:
      - '8080:8080'
      - '9229:9229'
    volumes:
      - ./movienator_express:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - movienator_network
    command: npm run install-start

  react:
    build:
      context: ./movienator_react
      dockerfile: Dockerfile
    container_name: movienator-react-dev
    stdin_open: true
    ports:
      - '3000:3000'
    volumes:
      - ./movienator_react:/usr/src/app/
      - /usr/src/app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: 'true'
    depends_on:
      - movienator-express-dev
    command: npm run install-start

volumes:
  dbdata:

networks:
  movienator_network:
    driver: bridge

