version: '3.9'

services:
  movienator-express-dev:
    build:
      context: ./movienator_express
      dockerfile: Dockerfile
    container_name: movienator-express-dev
    environment:
      TZ: 'Europe/Berlin'
      DB_PASSWORD: ${DB_PASSWORD}
      MOVIE_API_KEY: ${MOVIE_API_KEY}
    ports:
      - '8080:8080'
      - '9229:9229'
    volumes:
      - ./movienator_express:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - database
    networks:
      - movienator_network
    command: npm run install-start

  database:
    build:
      context: ./movienator_mysql
      dockerfile: Dockerfile
    container_name: movienator-database-dev
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: movienator-database
      MYSQL_USER: public
      MYSQL_PASSWORD: public
    ports:
      - '3306:3306'
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - movienator_network

  phpadmin:
    build:
      context: ./movienator_phpadmin
      dockerfile: Dockerfile
    container_name: movienator-phpadmin
    networks:
      - movienator_network
    ports:
      - '8081:80'
    environment:
      PMA_HOST: database
      PMA_PORT: 3306

  react:
    build:
      context: ./movienator_react
      dockerfile: Dockerfile
    container_name: movienator-react-dev
    stdin_open: true
    ports:
      - '3000:3000'
    volumes:
      - ./movienator_react:/usr/src/app/
      - /usr/src/app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: 'true'
      HATESPEECH_API_KEY: ${HATESPEECH_API_KEY}
    depends_on:
      - movienator-express-dev
    command: npm run install-start

volumes:
  dbdata:

networks:
  movienator_network:
    name: movienator_net
    driver: bridge
