### Request non existing Movie
http://localhost:8080/movie/one/-1

###Database config
https://api.themoviedb.org/3/configuration?api_key=***REMOVED***

###Test Movie
https://api.themoviedb.org/3/movie/663712?api_key=***REMOVED***

###Test Movie
https://api.themoviedb.org/3/movie/19995/similar?api_key=***REMOVED***

